=== Daij-Djan/xsd2cocoa/demos/configFeatures-demo/configFeatures.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/configs/configFeatures"
        xmlns:config="http://www.example.org/configs/configFeatures"
		elementFormDefault="qualified">

    <annotation>
        <documentation>
            configFeatures.xsd
        </documentation>
    </annotation>

    <complexType name="Config">
		<sequence>
	        <element name="features" type="config:Features" minOccurs="1" maxOccurs="1"/>
			<element name="userRights"  maxOccurs="1" minOccurs="1">
				<simpleType>
					<restriction base="string">
						<enumeration value="ADMIN"></enumeration>
						<enumeration value="OPERATOR"></enumeration>
						<enumeration value="MAGICIAN"></enumeration>
						<enumeration value="USER"></enumeration>
						<enumeration value="GUEST"></enumeration>
					</restriction>
				</simpleType>
			</element>
		</sequence>
    </complexType>

    <complexType name="Features">
		<sequence>
			<element name="feature" type="config:Feature" maxOccurs="unbounded" minOccurs="1"/>
		</sequence>
    </complexType>

	<complexType name="Feature">
		<attribute name="id" type="config:FeatureName" use="required"></attribute>
		<attribute name="enabled" type="boolean" use="required"></attribute>
	</complexType>
	
	<simpleType name="FeatureName">
		<restriction base="string">
			<enumeration value="CarManagement"></enumeration>
			<enumeration value="main"></enumeration>
			<enumeration value="networking"></enumeration>
			<enumeration value="officeSuite"></enumeration>
			<enumeration value="alarmClock"></enumeration>
			<enumeration value="TrafficInformation"></enumeration>
			<enumeration value="rss"></enumeration>
			<enumeration value="contactPage"></enumeration>
			<enumeration value="personalHomepage"></enumeration>
		</restriction>
	</simpleType>

	<!--root-->
	<element name='config' type="config:Config"/>
</schema>

=== Daij-Djan/xsd2cocoa/demos/configFeatures-demo/configFeatures.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.example.org/configs/configFeatures"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.org/configs/configFeatures configFeatures.xsd">
    <features>
        <feature id="main" enabled="true" />
        <feature id="networking" enabled="true" />
        <feature id="officeSuite" enabled="true" />
        <feature id="alarmClock" enabled="true" />
        <feature id="TrafficInformation" enabled="true"/>
        <feature id="rss" enabled="false"/>
        <feature id="contactPage" enabled="false"/>
        <feature id="personalHomepage" enabled="true"/>
    </features>
    <userRights>USER</userRights>
</config>
