=== Daij-Djan/xsd2cocoa/framework/xmls/template.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.example.com/xsd2cocoa"
 xmlns:xsd2cocoa="http://www.example.com/xsd2cocoa"
 elementFormDefault="qualified">

  <annotation>
    <documentation>
      template.xsd defines a format for definig a template to generate a parser from a xsd file
    </documentation>
  </annotation>

  <element name="template" type="xsd2cocoa:template">
    <annotation>
      <documentation>
        the root element that includes all the options for the xsd2code parser generation
      </documentation>
    </annotation>
  </element>

  <complexType name="template">
    <sequence>
      <element name="format_style" type="xsd2cocoa:format_style" minOccurs="0" maxOccurs="1">
        <annotation>
          <documentation>
            this defines a the uncrustify style to use:
            it can be objc or swift to use the respective built-in config. BUT it can also be a posix file path to a custom uncrustify cfg file
          </documentation>
        </annotation>
      </element>

      <element name="additional_file" type="xsd2cocoa:additional_file" minOccurs="0" maxOccurs="unbounded">
        <annotation>
          <documentation>
            This element defines a file that is copied next to the source files. It can occur n times, so that n files are copied.
          </documentation>
        </annotation>
      </element>

      <element name="simpletype" type="xsd2cocoa:simpletype" minOccurs="1" maxOccurs="unbounded">
        <annotation>
          <documentation>
            This element defines the templating options for a xsd simpletype and maps that to specific source code. All known types that need special source code are listed here. At least the xsd root types should be represented here.
          </documentation>
        </annotation>
      </element>

      <element name="complextype" type="xsd2cocoa:complextype" minOccurs="1" maxOccurs="1">
        <annotation>
          <documentation>
            This element defines the templating options for a xsd complextype and defines how an xml element with a complex type is parsed. Elements with complex types are all read the same way (they consist of more complex types and/or simple types)
          </documentation>
        </annotation>
      </element>

      <element name="enumeration" type="xsd2cocoa:enumeration" minOccurs="1" maxOccurs="1">
        <annotation>
          <documentation>
            This element defines the templating options for a xsd enumeration. Enumerations are all read the same way
          </documentation>
        </annotation>
      </element>
    </sequence>
  </complexType>

  <complexType name="filecontent">
    <simpleContent>
      <extension base="string">
        <attribute name="extension" type="string" use="required"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="format_style">
    <simpleContent>
      <extension base="string">
        <attribute name="type" type="string" use="required"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="additional_file">
    <attribute name="path" type="string" use="required" />
    <attribute name="target_path" type="string" use="optional" />
  </complexType>

  <complexType name="simpletype">
    <sequence>
      <element name="read" type="xsd2cocoa:read" minOccurs="1" maxOccurs="1"/>
    </sequence>
    <attribute name="name" type="string" use="required" />
    <attribute name="objType" type="string" use="required" />
    <attribute name="arrayType" type="string" use="required" />
    <attribute name="baseType" type="string" use="optional" />
  </complexType>

  <complexType name="complextype">
    <sequence>
      <element name="read" type="xsd2cocoa:read" minOccurs="1" maxOccurs="1"/>
      <element name="implementation" type="xsd2cocoa:implementation" minOccurs="1" maxOccurs="1">
        <annotation>
          <documentation>
            This element defines the templating options for reading the CONTENT of any xsd enumeration.
          </documentation>
        </annotation>
      </element>
      <element name="reader" type="xsd2cocoa:reader" minOccurs="1" maxOccurs="1">
        <annotation>
          <documentation>
            This element defines the templating options for convenience methods to parse a complex type from a valid xml file / xml data
          </documentation>
        </annotation>
      </element>
    </sequence>
    <attribute name="objType" type="string" use="required" />
    <attribute name="arrayType" type="string" use="required" />
  </complexType>

  <complexType name="enumeration">
    <sequence>
      <element name="read" type="xsd2cocoa:read" minOccurs="1" maxOccurs="1"/>
      <element name="implementation" type="xsd2cocoa:implementation" minOccurs="1" maxOccurs="1">
        <annotation>
          <documentation>
            This element defines the templating options for reading the CONTENT of any xsd complextype. The curse recurses using templates of other simple and complex types.
          </documentation>
        </annotation>
      </element>
    </sequence>
    <attribute name="objType" type="string" use="required" />
    <attribute name="arrayType" type="string" use="required" />
  </complexType>

  <complexType name="implementation">
    <sequence>
      <element name="header" type="xsd2cocoa:filecontent" minOccurs="0" maxOccurs="1"/>
      <element name="class" type="xsd2cocoa:filecontent" minOccurs="1" maxOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="reader">
    <sequence>
      <element name="header" type="xsd2cocoa:filecontent" minOccurs="0" maxOccurs="1"/>
      <element name="class" type="xsd2cocoa:filecontent" minOccurs="1" maxOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="read">
    <sequence>
      <element name="prefix" type="string" minOccurs="0" maxOccurs="1"/>
      <element name="attribute" type="string" minOccurs="0" maxOccurs="1"/>
      <element name="element" type="string" minOccurs="0" maxOccurs="1"/>
      <element name="value" type="string" minOccurs="0" maxOccurs="1"/>
    </sequence>
  </complexType>
</schema>

=== Daij-Djan/xsd2cocoa/framework/xmls/template-swift.xml
<template xmlns="http://www.example.com/xsd2cocoa"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.com/xsd2cocoa template.xsd">
    
    <format_style>swift</format_style>
    
    <additional_file path="libxml-bridging-header.header" target_path="libxml-bridging-header.h"/>
    
    <!-- known simpletypes-->
    <simpletype name="string" objType="String" arrayType="[String]">
        <read>
            <prefix></prefix>
            <attribute><![CDATA[self.{{ attribute.variableName }} = String.fromCString(UnsafePointer<CChar>({{ attribute.name }}AttrValue))]]></attribute>
            <element>/*TODO*/</element>
            <value><![CDATA[let value = String.fromCString(UnsafePointer<CChar>(contentValue))
                self.value = value]]></value>
        </read>
    </simpletype>
    <simpletype name="anyURI" objType="NSURL" arrayType="[NSURL]">
        <read>
            <prefix></prefix>
            <attribute><![CDATA[self.{{ attribute.variableName }} = NSURL(string: String.fromCString(UnsafePointer<CChar>({{ attribute.name }}AttrValue))!)]]></attribute>
            <element>/*TODO*/</element>
            <value><![CDATA[let value = String.fromCString(UnsafePointer<CChar>(contentValue))
                self.value = NSURL(string: value)]]></value>
        </read>
    </simpletype>
    <simpletype name="boolean" objType="Bool" arrayType="[Bool]">
        <read>
            <prefix></prefix>
            <attribute>self.{{ attribute.variableName }} = [NSNumber numberWithBool: [[NSString stringWithCStringring: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding] isEqualToString: @"true"]];</attribute>
            <element>/*TODO*/</element>
            <value>NSString *value = [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding];
                value = [value stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
                self.value = [NSNumber numberWithBool: [value isEqualToString: @"true"]];</value>
        </read>
    </simpletype>
    <simpletype name="integer" objType="Int" arrayType="[Int]">
        <read>
            <prefix>NSNumberFormatter* numFormatter = [[NSNumberFormatter alloc] init];
                numFormatter.numberStyle = NSNumberFormatterDecimalStyle;</prefix>
            <attribute>self.{{ attribute.variableName }} = [numFormatter numberFromString: [NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding]];</attribute>
            <element>/*TODO*/</element>
            <value>NSString *value = [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding];
                value = [value stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
                self.value = [numFormatter numberFromString: value];</value>
        </read>
    </simpletype>
    <simpletype name="decimal" objType="Double" arrayType="[Double]">
        <read>
            <prefix>NSNumberFormatter* decFormatter = [[NSNumberFormatter alloc] init];
                decFormatter.decimalSeparator = @".";
                decFormatter.numberStyle = NSNumberFormatterDecimalStyle;</prefix>
            <attribute>self.{{ attribute.variableName }} = [decFormatter numberFromString: [NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding]];</attribute>
            <element>/*TODO*/</element>
            <value>NSString *value = [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding];
                value = [value stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
                self.value = [decFormatter numberFromString: value];</value>
        </read>
    </simpletype>
    <simpletype name="dateTime" objType="NSDate" arrayType="[NSDate]">
        <read>
            <prefix>NSDateFormatter* dateFormatter = [[NSDateFormatter alloc] init];
                dateFormatter.timeStyle = NSDateFormatterFullStyle;
                dateFormatter.dateFormat = @"yyyy-MM-dd'T'HH:mm:ssZ";</prefix>
            <attribute>self.{{ attribute.variableName }} = [dateFormatter dateFromString: [NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding]];</attribute>
            <element>/*TODO*/</element>
            <value>NSString *value = [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding];
                value = [value stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
                self.value = [dateFormatter dateFromString: value];</value>
        </read>
    </simpletype>
    
    <!--complex type-->
    <complextype arrayType="[{{ type.targetClassName }}]">
        <read>
            <element><![CDATA[{% if element.isSingleValue %}self.{{ element.variableName }} = {{ element.codeType }}(reader: reader){% else %}{{ element.variableName }}Array.append({{ element.schemaType.targetClassName }}(reader: reader)){% /if %}]]></element>
        </read>
    </complextype>
    
    <implementation>
        <header extension=""></header>
        <class extension="swift"><![CDATA[
            import Foundation
            
            @objc
            class {{ type.targetClassName }} {% if type.hasComplexBaseClass %}: {{ type.baseClassName }} {% /if %}{
            {% for attribute in type.attributes %}
            var {{ attribute.variableName }}: {{ attribute.codeType }}?
            {% /for %}
            {% for element in type.elements %}    var {{ element.variableName }}: {{ element.codeType }}?
            {% /for %}
            {% if type.hasSimpleBaseClass %}
            var value: {{ type.baseClassName }}?{% /if %}
            
            {% if type.hasComplexBaseClass %}override {% /if %}func readAttributes(reader: xmlTextReaderPtr) {{% if type.hasComplexBaseClass %}
            super.readAttributes(reader)
            {% /if %}{{ type.combinedReadPrefixCode }}
            
            {% for attribute in type.attributes %}          let {{ attribute.name }}AttrName = UnsafePointer<xmlChar>(NSString(stringLiteral: "{{ attribute.name }}").UTF8String)
            let {{ attribute.name }}AttrValue = xmlTextReaderGetAttribute(reader, {{ attribute.name }}AttrName)
            if({{ attribute.name }}AttrValue != nil) {
            {{ attribute.readCodeForAttribute }}
            }{% /for %}
            }
            
            {% if type.hasComplexBaseClass %}override {% /if %}init(reader: xmlTextReaderPtr) {
            let _complexTypeXmlDept = xmlTextReaderDepth(reader)
            {% if type.hasComplexBaseClass %}super.init(reader: reader){% /if %}
            {{ type.combinedReadPrefixCode }}{% if type.hasComplexBaseClass %}{% else %}
            self.readAttributes(reader){% /if %}
            {% for element in type.elements %}
            {% if element.isSingleValue %}{% else %}var {{ element.variableName }}Array = {{ element.codeType }}(){% /if %}{% /for %}
            
            {% if type.hasComplexBaseClass %}var _readerOk:Int32=1{% else %}var _readerOk = xmlTextReaderRead(reader){% /if %}
            var _currentNodeType = xmlTextReaderNodeType(reader)
            var _currentXmlDept = xmlTextReaderDepth(reader)
            
            while(_readerOk > 0 && _currentNodeType != 0/*XML_READER_TYPE_NONE*/ && _complexTypeXmlDept < _currentXmlDept) {
            var handledInChild = false
            if(_currentNodeType == 1/*XML_READER_TYPE_ELEMENT*/ || _currentNodeType == 3/*XML_READER_TYPE_TEXT*/) {
            let _currentElementNameXmlChar = xmlTextReaderConstLocalName(reader)
            let _currentElementName = String.fromCString(UnsafePointer<CChar>(_currentElementNameXmlChar))
            {% for element in type.elements %}if("{{element.name}}" == _currentElementName) {
            {{ element.readCodeForContent }}
            {% if element.hasComplexType %}
            handledInChild = true{% /if %}
            } else {% /for %} {% if type.hasSimpleBaseClass %} if("#text" == _currentElementName){
            let contentValue = xmlTextReaderConstValue(reader)
            if(contentValue != nil) {
            {{ type.readSimpleContent }}
            }
            } else {% /if %} if(true) {
            println("Ignoring unexpected: \(_currentElementName)")
            break
            }
            }
            _readerOk = handledInChild ? xmlTextReaderReadState(reader) : xmlTextReaderRead(reader)
            _currentNodeType = xmlTextReaderNodeType(reader)
            _currentXmlDept = xmlTextReaderDepth(reader)
            }
            {% for element in type.elements %}
            {% if element.isSingleValue %}{% else %}if({{ element.variableName }}Array.count > 0) { self.{{ element.variableName }} = {{ element.variableName }}Array }{% /if %}{% /for %}
            }
            
            {% if type.hasComplexBaseClass %}override {% /if %}var dictionary: [String: AnyObject] {
            var dict = [String: AnyObject]()
            {% if type.hasComplexBaseClass %}for (name, value) in super.dictionary {
            dict[name] = value
            }{% /if %}
            
            {% for attribute in type.attributes %}
            if(self.{{ attribute.variableName }} != nil) { dict["{{ attribute.variableName }}"] = self.{{ attribute.variableName }} }{% /for %}
            {% for element in type.elements %}
            {% if element.hasComplexType %}
            if(self.{{ element.variableName }} != nil) {
            dict["{{ element.variableName }}"] = self.{{ element.variableName }}!{% if element.isSingleValue %}{% else %}.map({$0.dictionary}){% /if %}
            }
            {% else %} if(self.{{ element.variableName }} != nil) { dict["{{ element.variableName }}"] = self.{{ element.variableName }} }{% /if %}
            {% /for %}
            {% if type.hasSimpleBaseClass %}    if(self.value != nil) { dict["value"] = self.value }{% /if %}
