=== Daij-Djan/xsd2cocoa/xsd2cocoacore/template.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.example.com/xsd2cocoa"
 xmlns:xsd2cocoa="http://www.example.com/xsd2cocoa"
 elementFormDefault="qualified">

  <element name="template" type="xsd2cocoa:template"/>
  
  <complexType name="template">
    <sequence>
      <element name="additional_file" type="xsd2cocoa:additional_file" minOccurs="0" maxOccurs="unbounded"/>
      <element name="simpletype" type="xsd2cocoa:simpletype" minOccurs="1" maxOccurs="unbounded"/>
      <element name="complextype" type="xsd2cocoa:complextype" minOccurs="1" maxOccurs="1"/>
      <element name="implementation" type="xsd2cocoa:implementation" minOccurs="1" maxOccurs="1"/>
      <element name="reader" type="xsd2cocoa:reader" minOccurs="1" maxOccurs="1"/>
    </sequence>
  </complexType>
  
  <complexType name="additional_file">        
    <attribute name="path" type="string" use="required" />
  </complexType>

  <complexType name="simpletype">
    <sequence>
      <element name="read" type="xsd2cocoa:read" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="name" type="string" use="required" />
    <attribute name="objType" type="string" use="required" />
    <attribute name="arrayType" type="string" use="required" />
  </complexType>

  <complexType name="complextype">
    <sequence>
      <element name="read" type="xsd2cocoa:read" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="arrayType" type="string" use="required" />
  </complexType>

  <complexType name="implementation">
    <sequence>
      <element name="header" type="string" minOccurs="1" maxOccurs="1"/>
      <element name="class" type="string" minOccurs="1" maxOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="reader">
    <sequence>
      <element name="header" type="string" minOccurs="1" maxOccurs="1"/>
      <element name="class" type="string" minOccurs="1" maxOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="read">
    <sequence>
      <element name="prefix" type="string" minOccurs="0" maxOccurs="1"/>
      <element name="attribute" type="string" minOccurs="0" maxOccurs="1"/>
      <element name="element" type="string" minOccurs="0" maxOccurs="1"/>
      <element name="value" type="string" minOccurs="0" maxOccurs="1"/>
    </sequence>
  </complexType>
</schema>

=== Daij-Djan/xsd2cocoa/xsd2cocoacore/template-default.xml
<template xmlns="http://www.example.com/xsd2cocoa"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.com/xsd2cocoa template.xsd">
    <!-- <prefix_override for="namespace" to="DDXSDGenerated"/> -->
    
    <simpletype name="string" objType="NSString" arrayType="NSArray">
		<read>
			<prefix></prefix>
			<attribute>self.{{ attribute.variableName }} = [NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding];</attribute>
            <element><![CDATA[_readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);
          {% if element.isSingleValue %}self.{{ element.variableName }} = [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding];{% else %}[{{ element.variableName }}Array addObject: [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding]];{% /if %}
          _readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);]]></element>
            <value>self.value = [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding];</value>
		</read>
	</simpletype>
    <simpletype name="anyURI" objType="NSURL" arrayType="NSArray">
		<read>
			<prefix></prefix>
			<attribute>self.{{ attribute.variableName }} = [NSURL URLWithString:[NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding]];</attribute>
            <element><![CDATA[_readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);
                {% if element.isSingleValue %}self.{{ element.variableName }} = [NSURL URLWithString:[NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding]];{% else %}[{{ element.variableName }}Array addObject: [NSURL URLWithString:[NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding]]];{% /if %}
                _readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);]]></element>
            <value>self.value = [NSURL URLWithString:[NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding]];</value>
		</read>
	</simpletype>
	<simpletype name="boolean" objType="NSNumber" arrayType="NSArray">
		<read>
			<prefix></prefix>
			<attribute>self.{{ attribute.variableName }} = [NSNumber numberWithBool: [[NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding] isEqualToString: @"true"]];</attribute>
			<element><![CDATA[_readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);
          self.{{ element.variableName }} = [NSNumber numberWithBool: [[NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding] isEqualToString: @"true"]];
          _readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);]]></element>
            <value>self.value = [NSNumber numberWithBool: [[NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding] isEqualToString: @"true"]];</value>
		</read>
	</simpletype>
	<simpletype name="int" objType="NSNumber" arrayType="NSArray">
		<read>
			<prefix>NSNumberFormatter* intFormatter = [[NSNumberFormatter alloc] init];
    intFormatter.numberStyle = NSNumberFormatterDecimalStyle;</prefix>
			<attribute>self.{{ attribute.variableName }} = [intFormatter numberFromString: [NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding]];</attribute>
			<element><![CDATA[_readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);
          self.{{ element.variableName }} = [intFormatter numberFromString: [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding]];
          _readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);]]></element>
            <value>self.value = [intFormatter numberFromString: [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding]];</value>
		</read>
	</simpletype>
    <simpletype name="integer" objType="NSNumber" arrayType="NSArray">
		<read>
			<prefix>NSNumberFormatter* numFormatter = [[NSNumberFormatter alloc] init];
    numFormatter.numberStyle = NSNumberFormatterDecimalStyle;</prefix>
			<attribute>self.{{ attribute.variableName }} = [numFormatter numberFromString: [NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding]];</attribute>
			<element><![CDATA[_readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);
                self.{{ element.variableName }} = [numFormatter numberFromString: [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding]];
                _readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);]]></element>
            <value>self.value = [numFormatter numberFromString: [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding]];</value>
		</read>
	</simpletype>
	<simpletype name="decimal" objType="NSNumber" arrayType="NSArray">
		<read>
			<prefix>NSNumberFormatter* decFormatter = [[[NSNumberFormatter alloc] init];
    decFormatter.decimalSeparator = @".";
    decFormatter.numberStyle = NSNumberFormatterDecimalStyle;</prefix>
			<attribute>self.{{ attribute.variableName }} = [decFormatter numberFromString: [NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding]];</attribute>
			<element><![CDATA[_readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);
                self.{{ element.variableName }} = [decFormatter numberFromString: [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding]];
                _readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);]]></element>
            <value>self.value = [decFormatter numberFromString: [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding]];</value>
		</read>
	</simpletype>
	<simpletype name="dateTime" objType="NSDate" arrayType="NSArray">
		<read>
			<prefix>NSDateFormatter* dateFormatter = [[NSDateFormatter alloc] init];
    dateFormatter.timeStyle = NSDateFormatterFullStyle;
    dateFormatter.dateFormat = @"yyyy-MM-dd'T'HH:mm:ssZ";</prefix>
			<attribute>self.{{ attribute.variableName }} = [dateFormatter dateFromString: [NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding]];</attribute>
			<element><![CDATA[_readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);
                {% if element.isSingleValue %}self.{{ element.variableName }} = [dateFormatter dateFromString: [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding]];{% else %}[{{ element.variableName }}Array addObject: [dateFormatter dateFromString: [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding]]];{% /if %}
          _readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);]]></element>
            <value>self.value = [dateFormatter dateFromString: [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding]];</value>
		</read>
	</simpletype>
    
    <!--specific types-->
	<simpletype name="stringId" objType="NSString" arrayType="NSArray">
		<read>
			<prefix></prefix>
			<attribute>self.{{ attribute.variableName }} = [NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding];</attribute>
            <element><![CDATA[_readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);
                {% if element.isSingleValue %}self.{{ element.variableName }} = [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding];{% else %}[self.{{ element.variableName }}Array addObject: [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding]];{% /if %}
                _readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);]]></element>
			<value>self.value = [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding];</value>
		</read>
	</simpletype>
	<simpletype name="functionNames" objType="NSString" arrayType="NSArray">
		<read>
			<prefix></prefix>
			<attribute>self.{{ attribute.variableName }} = [NSString stringWithCString: {{ attribute.name }}AttrValue encoding: NSUTF8StringEncoding];</attribute>
            <element><![CDATA[_readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);
                {% if element.isSingleValue %}self.{{ element.variableName }} = [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding];{% else %}[self.{{ element.variableName }}Array addObject: [NSString stringWithCString: (const char*) xmlTextReaderConstValue(reader) encoding: NSUTF8StringEncoding]];{% /if %}
                _readerOk = xmlTextReaderRead(reader); assert(_readerOk==1); _currentNodeType = xmlTextReaderNodeType(reader);]]></element>
			<value>self.value = [NSString stringWithCString: contentValue encoding: NSUTF8StringEncoding];</value>
		</read>
	</simpletype>
